import "./globals.css";
import type { Metadata } from "next";
import { Aldrich } from "next/font/google";
const aldrich = Aldrich({ weight: '400',subsets: ["latin"] });
import 'aos/dist/aos.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={aldrich.className}>{children}</body>
    </html>
  );
}
