const photoNames = [
    "col1 (1).png",
    "col1 (2).png",
    "col1 (3).png",
    "col1 (4).png",
    "col1 (5).png",
    "col2 (1).png",
    "col2 (2).png",
    "col2 (3).png",
    "col2 (4).png",
    "col4 (4).png",
    "col2 (5).png",
    "col2 (6).png",
    "col3 (2).png",
    "col3 (3).png",
    "col3 (4).png",
    "col3 (1).png",
    "col3 (5).png",
    "col3 (7).png",
    "col4 (1).png",
    "col4 (2).png",
    "col4 (3).png",
    "col4 (5).png",
    "col5 (1).jpg",
    "col5 (2).jpg",
    "col5 (3).jpg",
    "col5 (4).jpg",
    "col5 (5).jpg",
    "col5 (6).jpg",
    "col5 (7).jpg",
    "col5 (8).jpg",
    "col5 (9).jpg",
    "col5 (10).jpg",
    "col5 (11).jpg",
    "col6 (1).jpg",
  ];

  export default photoNames;
